import type { SpPhoneCountry } from "./sp-phone-input.types.js";

export const PHONE_COUNTRIES: SpPhoneCountry[] = [
  { code: "AR", dial: "+54",  name: "Argentina",            flag: "🇦🇷" },
  { code: "AU", dial: "+61",  name: "Australia",            flag: "🇦🇺" },
  { code: "AT", dial: "+43",  name: "Austria",              flag: "🇦🇹" },
  { code: "BE", dial: "+32",  name: "Belgium",              flag: "🇧🇪" },
  { code: "BO", dial: "+591", name: "Bolivia",              flag: "🇧🇴" },
  { code: "BR", dial: "+55",  name: "Brazil",               flag: "🇧🇷" },
  { code: "CA", dial: "+1",   name: "Canada",               flag: "🇨🇦" },
  { code: "CL", dial: "+56",  name: "Chile",                flag: "🇨🇱" },
  { code: "CN", dial: "+86",  name: "China",                flag: "🇨🇳" },
  { code: "CO", dial: "+57",  name: "Colombia",             flag: "🇨🇴" },
  { code: "CR", dial: "+506", name: "Costa Rica",           flag: "🇨🇷" },
  { code: "CU", dial: "+53",  name: "Cuba",                 flag: "🇨🇺" },
  { code: "CZ", dial: "+420", name: "Czech Republic",       flag: "🇨🇿" },
  { code: "DK", dial: "+45",  name: "Denmark",              flag: "🇩🇰" },
  { code: "DO", dial: "+1",   name: "Dominican Republic",   flag: "🇩🇴" },
  { code: "EC", dial: "+593", name: "Ecuador",              flag: "🇪🇨" },
  { code: "EG", dial: "+20",  name: "Egypt",                flag: "🇪🇬" },
  { code: "SV", dial: "+503", name: "El Salvador",          flag: "🇸🇻" },
  { code: "FI", dial: "+358", name: "Finland",              flag: "🇫🇮" },
  { code: "FR", dial: "+33",  name: "France",               flag: "🇫🇷" },
  { code: "DE", dial: "+49",  name: "Germany",              flag: "🇩🇪" },
  { code: "GT", dial: "+502", name: "Guatemala",            flag: "🇬🇹" },
  { code: "HN", dial: "+504", name: "Honduras",             flag: "🇭🇳" },
  { code: "HK", dial: "+852", name: "Hong Kong",            flag: "🇭🇰" },
  { code: "HU", dial: "+36",  name: "Hungary",              flag: "🇭🇺" },
  { code: "IN", dial: "+91",  name: "India",                flag: "🇮🇳" },
  { code: "ID", dial: "+62",  name: "Indonesia",            flag: "🇮🇩" },
  { code: "IE", dial: "+353", name: "Ireland",              flag: "🇮🇪" },
  { code: "IL", dial: "+972", name: "Israel",               flag: "🇮🇱" },
  { code: "IT", dial: "+39",  name: "Italy",                flag: "🇮🇹" },
  { code: "JP", dial: "+81",  name: "Japan",                flag: "🇯🇵" },
  { code: "KR", dial: "+82",  name: "South Korea",          flag: "🇰🇷" },
  { code: "MX", dial: "+52",  name: "Mexico",               flag: "🇲🇽" },
  { code: "NL", dial: "+31",  name: "Netherlands",          flag: "🇳🇱" },
  { code: "NZ", dial: "+64",  name: "New Zealand",          flag: "🇳🇿" },
  { code: "NI", dial: "+505", name: "Nicaragua",            flag: "🇳🇮" },
  { code: "NG", dial: "+234", name: "Nigeria",              flag: "🇳🇬" },
  { code: "NO", dial: "+47",  name: "Norway",               flag: "🇳🇴" },
  { code: "PA", dial: "+507", name: "Panama",               flag: "🇵🇦" },
  { code: "PY", dial: "+595", name: "Paraguay",             flag: "🇵🇾" },
  { code: "PE", dial: "+51",  name: "Peru",                 flag: "🇵🇪" },
  { code: "PH", dial: "+63",  name: "Philippines",          flag: "🇵🇭" },
  { code: "PL", dial: "+48",  name: "Poland",               flag: "🇵🇱" },
  { code: "PT", dial: "+351", name: "Portugal",             flag: "🇵🇹" },
  { code: "PR", dial: "+1",   name: "Puerto Rico",          flag: "🇵🇷" },
  { code: "RO", dial: "+40",  name: "Romania",              flag: "🇷🇴" },
  { code: "RU", dial: "+7",   name: "Russia",               flag: "🇷🇺" },
  { code: "SA", dial: "+966", name: "Saudi Arabia",         flag: "🇸🇦" },
  { code: "ZA", dial: "+27",  name: "South Africa",         flag: "🇿🇦" },
  { code: "ES", dial: "+34",  name: "Spain",                flag: "🇪🇸" },
  { code: "SE", dial: "+46",  name: "Sweden",               flag: "🇸🇪" },
  { code: "CH", dial: "+41",  name: "Switzerland",          flag: "🇨🇭" },
  { code: "TW", dial: "+886", name: "Taiwan",               flag: "🇹🇼" },
  { code: "TH", dial: "+66",  name: "Thailand",             flag: "🇹🇭" },
  { code: "TR", dial: "+90",  name: "Turkey",               flag: "🇹🇷" },
  { code: "UA", dial: "+380", name: "Ukraine",              flag: "🇺🇦" },
  { code: "AE", dial: "+971", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "GB", dial: "+44",  name: "United Kingdom",       flag: "🇬🇧" },
  { code: "US", dial: "+1",   name: "United States",        flag: "🇺🇸" },
  { code: "UY", dial: "+598", name: "Uruguay",              flag: "🇺🇾" },
  { code: "VE", dial: "+58",  name: "Venezuela",            flag: "🇻🇪" },
  { code: "VN", dial: "+84",  name: "Vietnam",              flag: "🇻🇳" },
];
